create table test_table(name VARCHAR, surname VARCHAR, city VARCHAR, age int CHECK ((age > 0) and (age < 150) and (char_length(name) between 4 and 10)));


INSERT INTO test_table VALUES ('Ethyl', 'Hansen', 'Colbystad', 61),
('Jensen','Schmidt','Fort_Lucienneborough', 55),
('Martin','Hickle','San Tan Valley', 20),
('Geovany','Boyer','South Davion', 12),
('Alessandro','Kreiger','St. Louis Park', 11),
('Mateo','Kirlin','Hilllworth', 42),
('Everett','Boyer','East Dallas', 48),
('Lamont','Gorczany','Weimanntown', 49),
('Turner','Reichel','Angelaberg', 56),
('Dashawn','Morar','East Donnellview', 64),
('Clarabelle','Quigley','Cartwrightberg', 29),
('Maryjane','Ullrich','Elinorbury', 32),
('Ashtyn','Runolfsson','Fort Eusebio', 29),
('Elenora','Lind','West Selinahaven', 49),
('Turner','Sawayn','Fort Victorville', 11),
('Jazmin','McDermott','Olencester', 20),
('Kenya','Bartoletti','Port Dean', 4),
('Jairo','Casper','New Meghan', 73),
('Emerson','Howell','North Isac', 44),
('Golda','Auer','Fort Erna', 42),
('Adva','Tromp','South Frederique', 26),
('Roberto','Wehner','Turcottefield', 60),
('Jaleel','Cormier','Lake Nellie', 17),
('Grady','Lebsack','East Hailey', 14),
('Effie','Russel','West Idacester', 66),
('Daron','Kris','Moniquetown', 74),
('Arnulfo','Towne','Port Katherine', 41),
('Meredith','Schinner','Isadoreville', 23),
('Wilton','Nienow','Lake Keithfort', 74),
('Carey','Gislason','Bertaworth', 41),
('Holly','Rice','Gradychester', 60),
('Elmer','Glover','West Marlene', 72),
('Dayana','Runolfsdottir','Lake Ursulachester', 29),
('Dudley','Gleason','West Luis', 42),
('Lindsey','Gulgowski','Hayleyberg', 36),
('Dayna','Koss','Willstad', 5),
('Elna','Hessel','Fort Babybury', 32),
('Ferne','Von','Port Queenie', 58),
('Fermin','Wiegand','Normaboro', 36),
('Grayce','Quitzon','South Jordan', 28),
('Arvt','Kuhic','East Elody', 21),
('Chaya','Feeney','Fort Krystinahaven', 44),
('Arvel','Price','South Nayelibury', 11),
('Aryanna','Nienow','Okunevaland', 27),
('Delphine','Moore','Kevonstad', 40),
('Gennaro','Spencer','Gislasonberg', 73),
('Marilie','Zboncak','Imaborough', 38),
('Maryam','Ondricka','Lestercester', 73),
('Mortimer','Kunze','South Thad', 5),
('Mikayla','Bernhard','Huelsside', 53),
('Rafaela','Yost','Rhiannaburgh', 78),
('Fern','Kuhlman','Klockobury', 54),
('Helen','Considine','West Chance', 12),
('Lvee','Schumm','Clotildeberg', 41),
('Jovani','Streich','New Benjamintown', 74),
('Alfonzo','Gibson','Mariannabury', 54),
('Ethan','Skiles','Vista', 66),
('Jade','Jerde','Millscester', 46),
('Keaton','Kerluke','Ebertchester', 12),
('Emmitt','Cummings','Cordiamouth', 57),
('Chelsey','Block','St. Joseph', 65),
('Twila','Stark','Franklin', 38),
('Graciela','OConner','Ivahbury', 65);